
## TravisCI Config for JDK11
## Written by Brad Fuller
## v1.6 2019-05-01

## TO DO: Deploy to GitHub Releases on successful build from master - will add when framework is complete.

language: java
jdk:
  - oraclejdk11

before_install:
  # Download all required testing frameworks from Maven repository.
  - mkdir lib && cd lib && mkdir ant && cd ant
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-api/5.4.2/junit-jupiter-api-5.4.2.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-engine/5.4.2/junit-jupiter-engine-5.4.2.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-commons/1.4.2/junit-platform-commons-1.4.2.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-engine/1.4.2/junit-platform-engine-1.4.2.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-launcher/1.4.2/junit-platform-launcher-1.4.2.jar
  - wget --no-check-certificate https://search.maven.org/remotecontent?filepath=org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar

  # Download Apache Ant 1.10.5 for build.
  - cd BradF-99/CAB302-Assignment2
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.gz
  - tar -xzf apache-ant-1.10.5-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH

script:
  - ant test -lib ./lib/ant

after_script:
  - ant clean