
## TravisCI Config for JDK11
## Written by Brad Fuller
## v1.4 2019-05-01

language: java
jdk:
  - oraclejdk11

before_install:
  - sudo apt-get update
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.gz
  - tar -xzvf apache-ant-1.10.5-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH
  - echo $(ant -version)

script:
  - ant test -lib ./lib/ant

after_script:
  - ant clean