
## TravisCI Config for JDK11
## Written by Brad Fuller
## v1.9.3 2019-05-19

language: java
jdk:
  - oraclejdk11

branches:
  except:
    - /0\.[0-9]{3}/

before_install:
  # Download all required testing frameworks from Maven repository, as well as Ant 1.10.5 for building.
  - cd lib && mkdir ant && cd ant
  - wget -O apiguardian-api-1.0.0.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar
  - wget -O junit-jupiter-api-5.5.0-M1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-api/5.5.0-M1/junit-jupiter-api-5.5.0-M1.jar
  - wget -O junit-jupiter-engine-5.5.0-M1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-engine/5.5.0-M1/junit-jupiter-engine-5.5.0-M1.jar
  - wget -O junit-platform-commons-1.5.0-M1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-commons/1.5.0-M1/junit-platform-commons-1.5.0-M1.jar
  - wget -O junit-platform-engine-1.5.0-M1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-engine/1.5.0-M1/junit-platform-engine-1.5.0-M1.jar
  - wget -O junit-platform-launcher-1.5.0-M1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-launcher/1.5.0-M1/junit-platform-launcher-1.5.0-M1.jar
  - wget -O opentest4j-1.1.1.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar
  - wget -O ant-junitlauncher-1.10.6.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/apache/ant/ant-junitlauncher/1.10.6/ant-junitlauncher-1.10.6.jar
  - wget -O org.jacoco.ant-0.8.4.jar --no-check-certificate https://search.maven.org/remotecontent?filepath=org/jacoco/org.jacoco.ant/0.8.4/org.jacoco.ant-0.8.4.jar
  - cd ../..
  - wget --no-check-certificate http://us.mirrors.quenda.co/apache//ant/binaries/apache-ant-1.10.6-bin.tar.gz
  - tar -xzf apache-ant-1.10.6-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH

script:
  - ant test -lib ./lib/ant

before_deploy:
  - ant dist -lib ./lib/ant
  - ant clean
  - rm -rf ./lib/
  - cd bin/dist
  - git config --local user.name "Brad Fuller"
  - git config --local user.email "b7.fuller@connect.qut.edu.au"
  - export TRAVIS_TAG="0.$TRAVIS_BUILD_NUMBER"
  - git tag "$TRAVIS_TAG"

deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  api_key:
    secure: Armk8CI/tOtbMroC2ItVq6lZgUQXkBM33u0DyDCCDA4reH8WoQMzs3574ckpLqlJnXd+aeqNeiQkaOUKSVFR9bRowtEIaatTX7W2G+awgXzapRLu+qbk8DU/DFuBypx+KdhY9xZuwOLVwT1t9zgzdQHd53MUcn36DGQrfD9+9iTXC547NAYq12hJn9JHE5uXCR7KPs3r65GIhYxE/zDSZipQ3bkMiSqYgoYFIZjshDszqevYbd7S0Ex/dr7aKLFkV0FknSxTD7A0edkGI0jekvABZwNJtE8tQOOAc7mnMpXORxVSaNAOzvp1JRaLVkORW9veX4+YPTDmAk9DsHInDxk9X4MNaSwRGwY7v75MfKSJQlHcM/dgE7r5/DvwKzh7eRULxxiNkvvAtKCc+THunPZ/kB/22+XrgNtbBG536F4BIEy9bfEPOo71tVljIfST0W2dGaKdmajxE9bC9HPoJZGY7qfl7na3A2QMpfUubTHFNdq8+e3L7M7coWN89srGdqZ1L+h78SwIEN7wlPC1bJknq0qPr1mv2sUU5BQfqQFcptYJ8fL8MKVudZ/OM8ezK//fHhL0t9m3DXBSTWCcD3RdWKUCPKAdX7knILVTXlPh3BpMKW1As4GvEKnu1jdNIUCEsQM/Tiy6u8tJevkn1tXC9DLjKS9nYw8N0geNi0I=
  file: CAB302-Assignment2.jar
  on:
    repo: BradF-99/CAB302-Assignment2
    branch:
      - "master"

after_deploy:
  - cd ../..
  - ant clean


notifications:
  webhooks:
    urls:
      - https://skyhook.glitch.me/api/webhooks/579576826679001088/l3sn5qO986Mc6GPh0fn5DDLB0gHlEm_dLSaEjXpgQBUqIDapRVyJj515qmONU_DNMeKI/travis
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   always # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always